### PR TITLE
Add hyphen and underscore to alphanumeric test

### PR DESCRIPTION
**Pull request by k88hudson**
This might not be what you've intended, but it's definitely a pretty common use case to support hyphens and underscores in urls -- what do you think?

### CODE REVIEW

**Comment by snd** [comment]
hey kate,

you're absolutely right. thanks for catching and fixing that !
i've changed url-pattern a lot from from `0.7.1` to `0.8` and must have missed it in my thinking.

**here are some ideas on how we might improve it even further:**

we should support spaces (` `) and percent encoded parts (`%20`)  in urls as well.
this is easily implemented by adding ` ` and `%` at https://github.com/k88hudson/url-pattern/blob/hyphenunderscore/src/url-pattern.coffee#L80

i think we should omit the `-` at https://github.com/k88hudson/url-pattern/blob/hyphenunderscore/src/url-pattern.coffee#L54. this part is just about parsing the property name. i don't think i want to support hyphencase in property names. snakecase makes sense though.

finally it would be useful to expose that character set `a-zA-Z0-9-_` at https://github.com/k88hudson/url-pattern/blob/hyphenunderscore/src/url-pattern.coffee#L80 as `UrlPattern.prototype.allowedSegmentChars`. this way it could be modified if for example a user wants segments to end on encountering `_` or if a user doesn't want segments to end on encountering `.`.
the default character set should be fine for most situations though.

**at the start of next week i'll merge this and release `0.9`.**

**Comment by k88hudson** [comment]
@snd sounds good to me. I made your requested changes, still needs docs and better tests though -- I won't be able to get to that til tonight

**Comment by k88hudson** [comment]
@snd Ok, I added some tests and docs

Let me know what you think of having `allowedSegmentChars` be a second parameter, or if you would prefer an options object etc.

**Comment by snd** [comment]
looks good. thanks a lot !

**Comment by k88hudson** [comment]
no problem :+1:

**Comment by snd** [comment]
i just released v0.9 which contains these changes:
https://github.com/snd/url-pattern#09
excuse the delay. i was on vacation for a few days.

to add escaping i refactored and rewrote most of the implementation.
see also: https://github.com/snd/url-pattern#modifying-the-compiler

**Pull request merged**
